import Foundation
import TelegramCore
import ChatControllerInteraction
import AccountContext

// Reuse viewing/navigation callbacks, but give History its own interaction
// object with no sending, editing, deletion, reactions or bot actions.
func arielgramHistoryInteraction(_ base: ChatControllerInteraction, context: AccountContext, openMessage: @escaping (EngineRawMessage, OpenMessageParams) -> Bool) -> ChatControllerInteraction {
    let result = ChatControllerInteraction(
        openMessage: openMessage,
        openPeer: base.openPeer,
        openPeerMention: base.openPeerMention,
        openMessageContextMenu: { _, _, _, _, _, _ in  },
        openMessageReactionContextMenu: { _, _, _, _ in  },
        updateMessageReaction: { _, _, _, _ in  },
        activateMessagePinch: base.activateMessagePinch,
        openMessageContextActions: { _, _, _, _ in  },
        navigateToMessage: { _, _, _ in  },
        navigateToMessageStandalone: { _ in  },
        navigateToThreadMessage: { _, _, _ in  },
        tapMessage: nil,
        clickThroughMessage: { _, _ in  },
        toggleMessagesSelection: { _, _ in  },
        sendCurrentMessage: { _, _ in  },
        sendMessage: { _, _ in  },
        sendSticker: { _, _, _, _, _, _, _, _, _ in false },
        sendEmoji: { _, _, _ in  },
        sendGif: { _, _, _, _, _ in false },
        sendBotContextResultAsGif: { _, _, _, _, _, _ in false },
        editGif: { _, _ in  },
        requestMessageActionCallback: { _, _, _, _, _ in  },
        requestMessageActionUrlAuth: { _, _ in  },
        activateSwitchInline: { _, _, _ in  },
        openUrl: base.openUrl,
        openExternalInstantPage: base.openExternalInstantPage,
        shareCurrentLocation: { _ in  },
        shareAccountContact: { _ in  },
        sendBotCommand: { _, _ in  },
        openInstantPage: base.openInstantPage,
        openWallpaper: base.openWallpaper,
        openTheme: base.openTheme,
        openHashtag: { _, _ in  },
        updateInputState: { _ in  },
        updateInputMode: { _ in  },
        updatePresentationState: { _ in  },
        openMessageShareMenu: { _ in  },
        presentController: base.presentController,
        presentControllerInCurrent: base.presentControllerInCurrent,
        navigationController: base.navigationController,
        chatControllerNode: { nil },
        presentGlobalOverlayController: base.presentGlobalOverlayController,
        callPeer: { _, _ in  },
        openConferenceCall: { _ in  },
        longTap: { _, _ in  },
        todoItemLongTap: { _, _ in  },
        pollOptionLongTap: { _, _ in  },
        openCheckoutOrReceipt: { _, _ in  },
        openSearch: {  },
        setupReply: { _ in  },
        canSetupReply: { _ in .none },
        canSendMessages: { false },
        navigateToFirstDateMessage: { _, _ in  },
        requestRedeliveryOfFailedMessages: { _ in  },
        addContact: { _ in  },
        rateCall: { _, _, _ in  },
        requestSelectMessagePollOptions: { _, _ in  },
        requestAddMessagePollOption: { _, _, _, _, _ in  },
        requestOpenMessagePollResults: { _, _ in  },
        openAppStorePage: base.openAppStorePage,
        displayMessageTooltip: base.displayMessageTooltip,
        seekToTimecode: base.seekToTimecode,
        scheduleCurrentMessage: { _ in  },
        sendScheduledMessagesNow: { _ in  },
        editScheduledMessagesTime: { _ in  },
        performTextSelectionAction: { _, _, _, _, _ in  },
        displayImportedMessageTooltip: base.displayImportedMessageTooltip,
        displaySwipeToReplyHint: {  },
        dismissReplyMarkupMessage: { _ in  },
        openMessagePollResults: { _, _ in  },
        openPollCreation: { _, _ in  },
        openPollMedia: { _, _ in  },
        displayPollSolution: base.displayPollSolution,
        displayPsa: base.displayPsa,
        displayDiceTooltip: base.displayDiceTooltip,
        animateDiceSuccess: { _, _ in  },
        displayPremiumStickerTooltip: base.displayPremiumStickerTooltip,
        displayEmojiPackTooltip: base.displayEmojiPackTooltip,
        openPeerContextMenu: { _, _, _, _, _ in  },
        openMessageReplies: { _, _, _ in  },
        openReplyThreadOriginalMessage: { _ in  },
        openMessageStats: { _ in  },
        editMessageMedia: { _, _ in  },
        copyText: base.copyText,
        displayUndo: base.displayUndo,
        isAnimatingMessage: { _ in false },
        getMessageTransitionNode: { nil },
        updateChoosingSticker: { _ in  },
        commitEmojiInteraction: { _, _, _, _ in  },
        openLargeEmojiInfo: base.openLargeEmojiInfo,
        openJoinLink: base.openJoinLink,
        openWebView: { _, _, _, _ in  },
        activateAdAction: { _, _, _, _ in  },
        adContextAction: { _, _, _ in  },
        removeAd: { _ in  },
        openRequestedPeerSelection: { _, _, _, _ in  },
        saveMediaToFiles: { _ in  },
        openNoAdsDemo: {  },
        openAdsInfo: {  },
        displayGiveawayParticipationStatus: { _ in  },
        openPremiumStatusInfo: { _, _, _, _ in  },
        openRecommendedChannelContextMenu: { _, _, _ in  },
        openGroupBoostInfo: { _, _ in  },
        openStickerEditor: {  },
        openAgeRestrictedMessageMedia: { _, _ in  },
        playMessageEffect: { _ in  },
        editMessageFactCheck: { _ in  },
        sendGift: { _ in  },
        openUniqueGift: base.openUniqueGift,
        openMessageFeeException: {  },
        requestMessageUpdate: { _, _, _ in  },
        cancelInteractiveKeyboardGestures: {  },
        dismissTextInput: base.dismissTextInput,
        scrollToMessageId: { _, _ in  },
        scrollToMessageIdWithAnchor: { _, _ in  },
        navigateToStory: { _, _ in  },
        attemptedNavigationToPrivateQuote: base.attemptedNavigationToPrivateQuote,
        forceUpdateWarpContents: {  },
        playShakeAnimation: {  },
        displayQuickShare: { _, _, _ in  },
        updateChatLocationThread: { _, _ in  },
        requestToggleTodoMessageItem: { _, _, _ in  },
        displayTodoToggleUnavailable: base.displayTodoToggleUnavailable,
        openStarsPurchase: { _ in  },
        openRankInfo: { _, _, _ in  },
        openSetPeerAvatar: {  },
        displayPollRestrictedToast: base.displayPollRestrictedToast,
        automaticMediaDownloadSettings: base.automaticMediaDownloadSettings,
        pollActionState: base.pollActionState,
        stickerSettings: base.stickerSettings,
        presentationContext: ChatPresentationContext(context: context, backgroundNode: nil)
    )
    result.chatIsRotated = false
    return result
}
